import"./assets/styles-BK7AYJoX.js";import{a,i as g}from"./assets/vendor-4yCzdkXl.js";a.defaults.baseURL="https://dummyjson.com/products";async function _(){const{data:t}=await a.get("/category-list");return t}async function y(t,o=1){const{data:e}=await a.get(`/category/${t}?limit=12&skip=${(o-1)*12}`);return e}async function d(t=1){const{data:o}=await a.get(`?limit=12&skip=${(t-1)*12}`);return o}async function f(t){const{data:o}=await a.get(`/${t}`);return o}async function L(t,o=1){const{data:e}=await a.get(`/search?q=${t}&limit=12&skip=${(o-1)*12}`);return e}const s={categoriesList:document.querySelector(".categories"),productsList:document.querySelector(".products"),modal:document.querySelector(".modal"),modalProduct:document.querySelector(".modal-product"),modalCloseBtn:document.querySelector(".modal__close-btn"),searchForm:document.querySelector(".search-form"),notFound:document.querySelector(".not-found"),searchFormBtnClear:document.querySelector(".search-form__btn-clear")};function h(t){const e=["All",...t].map(c=>`
        <li class="categories__item">
            <button class="categories__btn" type="button">${c}</button>
        </li>
        `).join("");s.categoriesList.insertAdjacentHTML("beforeend",e)}function r(t){const o=t.map(({id:e,title:c,thumbnail:n,brand:i,category:m,price:p})=>`
         <li class="products__item" data-id="${e}">
    <img class="products__image" src="${n}" alt="${c}"/>
    <p class="products__title">${c}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${i}</span></p>
    <p class="products__category">Category: ${m}</p>
    <p class="products__price">Price: ${p}$</p>
 </li>
          `).join("");s.productsList.insertAdjacentHTML("beforeend",o)}function b(t){const o=`<img class="modal-product__img" src="${t.images[0]}" alt="" />
      <div class="modal-product__content">
        <p class="modal-product__title">${t.title}</p>
        <ul class="modal-product__tags">${t.tags.map(e=>`<li class="modal-product__tag">${e}</li>`).join("")}</ul>
        <p class="modal-product__description">${t.description}</p>
        <p class="modal-product__shipping-information">Shipping: ${t.shippingInformation}</p>
        <p class="modal-product__return-policy">Return Policy: ${t.returnPolicy}</p>
        <p class="modal-product__price">Price: ${t.price} $</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>`;s.modalProduct.innerHTML=o}function l(){s.productsList.innerHTML=""}async function $(){try{const t=await _();h(t);const{products:o}=await d();r(o)}catch(t){console.log(t)}}async function C(t){try{if(t.target.tagName!=="BUTTON")return;const o=t.target.textContent,e=t.target,c=document.querySelector(".not-found");if(console.log(o),o==="All"){const{products:i}=await d();console.log("all",i),r(i);return}const{products:n}=await y(o);if(console.log(n.length),n.length===0){console.log("notFound"),c.classList.add("not-found--visible");return}e.classList.add("categories__btn--active"),console.log(n),console.log(e),r(n)}catch(o){console.log(o)}}async function k(t){if(!t.target.closest(".products__item"))return;console.log(t.target.closest(".products__item")),console.log(t.target.closest(".products__item"));const o=t.target.closest(".products__item").dataset.id,e=await f(o);s.modal.classList.add("modal--is-open"),b(e),document.addEventListener("keydown",u)}function v(){s.modal.classList.remove("modal--is-open"),document.removeEventListener("keydown",u)}function P(t){t.target===t.currentTarget&&s.modal.classList.remove("modal--is-open")}function u(t){t.code==="Escape"&&s.modal.classList.remove("modal--is-open")}async function w(t){t.preventDefault(),console.log(t.target.elements.searchValue.value);const o=t.target.elements.searchValue.value.trim();if(o===""){g.warning({title:"Warning",message:"Please enter a search query",position:"topRight",timeout:3e3}),console.log("Please enter a search query");return}const{products:e}=await L(o);if(console.log(e),e.length===0){l(),s.notFound.classList.add("not-found--visible");return}l(),r(e)}async function B(){s.searchForm.elements.searchValue.value="",s.notFound.classList.contains("not-found--visible")&&s.notFound.classList.remove("not-found--visible"),l();const t=await d();r(t.products)}document.addEventListener("DOMContentLoaded",$);s.categoriesList.addEventListener("click",C);s.productsList.addEventListener("click",k);s.modalCloseBtn.addEventListener("click",v);s.modal.addEventListener("click",P);s.searchForm.addEventListener("submit",w);s.searchFormBtnClear.addEventListener("click",B);
//# sourceMappingURL=index.js.map
